import type { BadgeTone, LostReason, OwnerRef, PipelineStage, TaskPriority } from "@/types/crm";

/** Fictitious data for "Modo Demonstração" — never written to or read from
 * Supabase. Every screen the feature covers (Dashboard, Leads, Pipeline,
 * Clientes, Marketing Intelligence) derives its data from this single seed,
 * so numbers stay internally consistent (e.g. "Leads Qualificados" on the
 * Dashboard always matches how many demo leads are actually in/after the
 * Qualificado stage). */

export const DEMO_PIPELINE_STAGES: PipelineStage[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    key: "novo",
    label: "Novo",
    color: "info" as BadgeTone,
    position: 1,
    isWon: false,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    key: "contato",
    label: "Em contato",
    color: "warn" as BadgeTone,
    position: 2,
    isWon: false,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    key: "qualificado",
    label: "Qualificado",
    color: "warn" as BadgeTone,
    position: 3,
    isWon: false,
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    key: "proposta",
    label: "Proposta",
    color: "info" as BadgeTone,
    position: 4,
    isWon: false,
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    key: "fechado",
    label: "Fechado",
    color: "ok" as BadgeTone,
    position: 5,
    isWon: true,
  },
];

export const DEMO_OWNERS: OwnerRef[] = [
  {
    id: "00000000-0000-4000-8000-000000000101",
    name: "Camila Rocha",
    email: "camila.rocha@brusync.com.br",
  },
  {
    id: "00000000-0000-4000-8000-000000000102",
    name: "Rafael Souza",
    email: "rafael.souza@brusync.com.br",
  },
  {
    id: "00000000-0000-4000-8000-000000000103",
    name: "Juliana Alves",
    email: "juliana.alves@brusync.com.br",
  },
  {
    id: "00000000-0000-4000-8000-000000000104",
    name: "Thiago Martins",
    email: "thiago.martins@brusync.com.br",
  },
];

export interface DemoUtmSeed {
  source: string | null;
  medium: string | null;
  campaign: string | null;
  content: string | null;
  term: string | null;
  gclid?: string;
  fbclid?: string;
  ttclid?: string;
  landingPage: string;
  referer: string | null;
}

export interface DemoLeadSeed {
  id: string;
  name: string;
  company: string;
  jobTitle: string;
  city: string;
  email: string;
  phone: string;
  stageKey: (typeof DEMO_PIPELINE_STAGES)[number]["key"];
  ownerIndex: number | null;
  potentialValue: number;
  score: number;
  tags: string[];
  daysAgoCreated: number;
  daysInStage: number;
  lastInteractionDaysAgo: number | null;
  lost?: { reason: LostReason; daysAgo: number };
  utm: DemoUtmSeed | null;
  nextTask?: { title: string; daysFromNow: number; priority: TaskPriority };
  becameClient?: boolean;
}

const GOOGLE_CAMPAIGN = {
  source: "google",
  medium: "cpc",
  campaign: "busca-software-personalizado",
  content: "anuncio-b",
  term: "sistema+para+empresa",
  gclid: "gclid-demo",
  landingPage: "/",
  referer: "https://www.google.com/",
};

const META_CAMPAIGN = {
  source: "facebook",
  medium: "paid-social",
  campaign: "lancamento-crm-inteligente",
  content: "criativo-carrossel",
  term: "crm-vendas",
  fbclid: "fbclid-demo",
  landingPage: "/materiais/como-criar-software-white-label",
  referer: "https://www.facebook.com/",
};

const META_CAMPAIGN_2 = {
  source: "instagram",
  medium: "paid-social",
  campaign: "reels-transformacao-digital",
  content: "criativo-reels-a",
  term: "automacao",
  fbclid: "fbclid-demo-2",
  landingPage: "/blog/inteligencia-artificial-mudando-empresas-2026",
  referer: "https://www.instagram.com/",
};

const TIKTOK_CAMPAIGN = {
  source: "tiktok",
  medium: "paid-social",
  campaign: "tiktok-ads-pmes",
  content: "video-curto-1",
  term: null,
  ttclid: "ttclid-demo",
  landingPage: "/",
  referer: "https://www.tiktok.com/",
};

const LINKEDIN_CAMPAIGN = {
  source: "linkedin",
  medium: "paid-social",
  campaign: "linkedin-b2b-decisores",
  content: "post-patrocinado",
  term: null,
  landingPage: "/cases",
  referer: "https://www.linkedin.com/",
};

const ORGANIC: DemoUtmSeed = {
  source: null,
  medium: "organic",
  campaign: null,
  content: null,
  term: null,
  landingPage: "/blog/white-label-empresas-abandonando-softwares-genericos",
  referer: "https://www.google.com/",
};

const DIRECT: DemoUtmSeed = {
  source: null,
  medium: null,
  campaign: null,
  content: null,
  term: null,
  landingPage: "/",
  referer: null,
};

const INDICACAO: DemoUtmSeed = {
  source: "indicacao",
  medium: "referral",
  campaign: null,
  content: null,
  term: null,
  landingPage: "/",
  referer: null,
};

export const DEMO_LEADS: DemoLeadSeed[] = [
  // ---- Novo ----
  {
    id: "00000000-0000-4000-8000-000000000201",
    name: "Marcelo Tanaka",
    company: "Clínica Vida Plena",
    jobTitle: "Diretor Clínico",
    city: "Blumenau",
    email: "marcelo.tanaka@vidaplena.demo",
    phone: "47999011001",
    stageKey: "novo",
    ownerIndex: null,
    potentialValue: 8500,
    score: 25,
    tags: ["clínica", "saúde"],
    daysAgoCreated: 1,
    daysInStage: 1,
    lastInteractionDaysAgo: null,
    utm: GOOGLE_CAMPAIGN,
    nextTask: { title: "Fazer primeiro contato", daysFromNow: 1, priority: "medium" },
  },
  {
    id: "00000000-0000-4000-8000-000000000202",
    name: "Fernanda Lima",
    company: "Ótica Boa Vista",
    jobTitle: "Proprietária",
    city: "Joinville",
    email: "fernanda.lima@oticaboavista.demo",
    phone: "47999011002",
    stageKey: "novo",
    ownerIndex: 1,
    potentialValue: 6200,
    score: 20,
    tags: ["varejo"],
    daysAgoCreated: 2,
    daysInStage: 2,
    lastInteractionDaysAgo: null,
    utm: ORGANIC,
    nextTask: { title: "Fazer primeiro contato", daysFromNow: 0, priority: "high" },
  },
  {
    id: "00000000-0000-4000-8000-000000000203",
    name: "Diego Ferreira",
    company: "Academia Potência",
    jobTitle: "Sócio-gerente",
    city: "Itajaí",
    email: "diego.ferreira@potencia.demo",
    phone: "47999011003",
    stageKey: "novo",
    ownerIndex: null,
    potentialValue: 5400,
    score: 18,
    tags: ["fitness"],
    daysAgoCreated: 3,
    daysInStage: 3,
    lastInteractionDaysAgo: null,
    utm: TIKTOK_CAMPAIGN,
    nextTask: { title: "Fazer primeiro contato", daysFromNow: -1, priority: "high" },
  },
  {
    id: "00000000-0000-4000-8000-000000000204",
    name: "Patrícia Gomes",
    company: "Doce Sabor Confeitaria",
    jobTitle: "Fundadora",
    city: "Balneário Camboriú",
    email: "patricia.gomes@docesabor.demo",
    phone: "47999011004",
    stageKey: "novo",
    ownerIndex: 2,
    potentialValue: 4200,
    score: 22,
    tags: ["food service"],
    daysAgoCreated: 1,
    daysInStage: 1,
    lastInteractionDaysAgo: null,
    utm: META_CAMPAIGN,
  },
  {
    id: "00000000-0000-4000-8000-000000000205",
    name: "Roberto Cavalcanti",
    company: "Cavalcanti Advogados Associados",
    jobTitle: "Sócio",
    city: "Florianópolis",
    email: "roberto.cavalcanti@cavalcantiadv.demo",
    phone: "47999011005",
    stageKey: "novo",
    ownerIndex: null,
    potentialValue: 12000,
    score: 30,
    tags: ["jurídico", "alto valor"],
    daysAgoCreated: 4,
    daysInStage: 4,
    lastInteractionDaysAgo: null,
    utm: LINKEDIN_CAMPAIGN,
    nextTask: { title: "Fazer primeiro contato", daysFromNow: -2, priority: "high" },
  },
  {
    id: "00000000-0000-4000-8000-000000000206",
    name: "Camila Nunes",
    company: "Nunes Contabilidade",
    jobTitle: "Contadora responsável",
    city: "Brusque",
    email: "camila.nunes@nunescontabil.demo",
    phone: "47999011006",
    stageKey: "novo",
    ownerIndex: 3,
    potentialValue: 7300,
    score: 24,
    tags: ["contabilidade"],
    daysAgoCreated: 0,
    daysInStage: 0,
    lastInteractionDaysAgo: null,
    utm: DIRECT,
  },

  // ---- Em contato ----
  {
    id: "00000000-0000-4000-8000-000000000207",
    name: "Eduardo Pires",
    company: "Pires Distribuidora de Alimentos",
    jobTitle: "Diretor Comercial",
    city: "Joinville",
    email: "eduardo.pires@piresdistrib.demo",
    phone: "47999011007",
    stageKey: "contato",
    ownerIndex: 1,
    potentialValue: 15800,
    score: 42,
    tags: ["distribuição", "alto valor"],
    daysAgoCreated: 6,
    daysInStage: 3,
    lastInteractionDaysAgo: 1,
    utm: GOOGLE_CAMPAIGN,
    nextTask: { title: "Lembrete: acompanhar contato inicial", daysFromNow: 2, priority: "medium" },
  },
  {
    id: "00000000-0000-4000-8000-000000000208",
    name: "Beatriz Andrade",
    company: "Andrade Imóveis",
    jobTitle: "Corretora-chefe",
    city: "Balneário Camboriú",
    email: "beatriz.andrade@andradeimoveis.demo",
    phone: "47999011008",
    stageKey: "contato",
    ownerIndex: 2,
    potentialValue: 9600,
    score: 38,
    tags: ["imobiliário"],
    daysAgoCreated: 5,
    daysInStage: 2,
    lastInteractionDaysAgo: 2,
    utm: META_CAMPAIGN_2,
    nextTask: { title: "Lembrete: acompanhar contato inicial", daysFromNow: 1, priority: "medium" },
  },
  {
    id: "00000000-0000-4000-8000-000000000209",
    name: "Gustavo Ramos",
    company: "Oficina Ramos Mecânica",
    jobTitle: "Proprietário",
    city: "Itajaí",
    email: "gustavo.ramos@oficinaramos.demo",
    phone: "47999011009",
    stageKey: "contato",
    ownerIndex: null,
    potentialValue: 5100,
    score: 30,
    tags: ["automotivo"],
    daysAgoCreated: 9,
    daysInStage: 6,
    lastInteractionDaysAgo: 6,
    utm: ORGANIC,
  },
  {
    id: "00000000-0000-4000-8000-000000000210",
    name: "Larissa Costa",
    company: "Escola Crescer Educação Infantil",
    jobTitle: "Diretora Pedagógica",
    city: "Blumenau",
    email: "larissa.costa@escolacrescer.demo",
    phone: "47999011010",
    stageKey: "contato",
    ownerIndex: 3,
    potentialValue: 6800,
    score: 34,
    tags: ["educação"],
    daysAgoCreated: 7,
    daysInStage: 4,
    lastInteractionDaysAgo: 3,
    utm: INDICACAO,
    nextTask: { title: "Lembrete: acompanhar contato inicial", daysFromNow: 3, priority: "low" },
  },
  {
    id: "00000000-0000-4000-8000-000000000211",
    name: "Henrique Sales",
    company: "Sales Engenharia e Projetos",
    jobTitle: "Engenheiro Responsável",
    city: "Florianópolis",
    email: "henrique.sales@salesengenharia.demo",
    phone: "47999011011",
    stageKey: "contato",
    ownerIndex: 1,
    potentialValue: 21000,
    score: 46,
    tags: ["engenharia", "alto valor"],
    daysAgoCreated: 8,
    daysInStage: 5,
    lastInteractionDaysAgo: 4,
    utm: LINKEDIN_CAMPAIGN,
  },

  // ---- Qualificado ----
  {
    id: "00000000-0000-4000-8000-000000000212",
    name: "Renata Duarte",
    company: "Duarte Estética Avançada",
    jobTitle: "Fundadora",
    city: "Itapema",
    email: "renata.duarte@duarteestetica.demo",
    phone: "47999011012",
    stageKey: "qualificado",
    ownerIndex: 2,
    potentialValue: 8900,
    score: 61,
    tags: ["estética", "qualificado"],
    daysAgoCreated: 14,
    daysInStage: 5,
    lastInteractionDaysAgo: 2,
    utm: META_CAMPAIGN,
    nextTask: { title: "Preparar orçamento", daysFromNow: 2, priority: "medium" },
  },
  {
    id: "00000000-0000-4000-8000-000000000213",
    name: "André Barbosa",
    company: "Barbosa Materiais de Construção",
    jobTitle: "Diretor Financeiro",
    city: "Joinville",
    email: "andre.barbosa@barbosamateriais.demo",
    phone: "47999011013",
    stageKey: "qualificado",
    ownerIndex: null,
    potentialValue: 17500,
    score: 58,
    tags: ["varejo", "alto valor"],
    daysAgoCreated: 16,
    daysInStage: 7,
    lastInteractionDaysAgo: 5,
    utm: GOOGLE_CAMPAIGN,
    nextTask: { title: "Preparar orçamento", daysFromNow: 4, priority: "medium" },
  },
  {
    id: "00000000-0000-4000-8000-000000000214",
    name: "Vanessa Teixeira",
    company: "Teixeira Moda Fitness",
    jobTitle: "CEO",
    city: "Brusque",
    email: "vanessa.teixeira@teixeirafitness.demo",
    phone: "47999011014",
    stageKey: "qualificado",
    ownerIndex: 3,
    potentialValue: 11200,
    score: 64,
    tags: ["e-commerce", "qualificado"],
    daysAgoCreated: 12,
    daysInStage: 4,
    lastInteractionDaysAgo: 1,
    utm: TIKTOK_CAMPAIGN,
  },
  {
    id: "00000000-0000-4000-8000-000000000215",
    name: "Felipe Aragão",
    company: "Aragão Transportes e Logística",
    jobTitle: "Diretor de Operações",
    city: "Navegantes",
    email: "felipe.aragao@aragaotransportes.demo",
    phone: "47999011015",
    stageKey: "qualificado",
    ownerIndex: 1,
    potentialValue: 26000,
    score: 69,
    tags: ["logística", "alto valor"],
    daysAgoCreated: 18,
    daysInStage: 9,
    lastInteractionDaysAgo: 6,
    utm: ORGANIC,
    nextTask: { title: "Preparar orçamento", daysFromNow: -1, priority: "high" },
  },
  {
    id: "00000000-0000-4000-8000-000000000216",
    name: "Simone Rocha",
    company: "Rocha Pet Shop & Clínica Veterinária",
    jobTitle: "Sócia-veterinária",
    city: "Itajaí",
    email: "simone.rocha@rochapet.demo",
    phone: "47999011016",
    stageKey: "qualificado",
    ownerIndex: 2,
    potentialValue: 7400,
    score: 55,
    tags: ["pet", "qualificado"],
    daysAgoCreated: 10,
    daysInStage: 3,
    lastInteractionDaysAgo: 1,
    utm: DIRECT,
  },

  // ---- Proposta ----
  {
    id: "00000000-0000-4000-8000-000000000217",
    name: "Marcos Vinícius Silveira",
    company: "Silveira Supermercados",
    jobTitle: "Diretor de TI",
    city: "Joinville",
    email: "marcos.silveira@silveirasuper.demo",
    phone: "47999011017",
    stageKey: "proposta",
    ownerIndex: 1,
    potentialValue: 34000,
    score: 78,
    tags: ["varejo", "alto valor"],
    daysAgoCreated: 24,
    daysInStage: 6,
    lastInteractionDaysAgo: 2,
    utm: GOOGLE_CAMPAIGN,
    nextTask: { title: "Follow-up da proposta enviada", daysFromNow: 1, priority: "high" },
  },
  {
    id: "00000000-0000-4000-8000-000000000218",
    name: "Isabela Monteiro",
    company: "Monteiro Odontologia Integrada",
    jobTitle: "Diretora Clínica",
    city: "Balneário Camboriú",
    email: "isabela.monteiro@monteiroodonto.demo",
    phone: "47999011018",
    stageKey: "proposta",
    ownerIndex: 3,
    potentialValue: 14300,
    score: 74,
    tags: ["saúde", "proposta enviada"],
    daysAgoCreated: 20,
    daysInStage: 5,
    lastInteractionDaysAgo: 1,
    utm: META_CAMPAIGN,
    nextTask: { title: "Follow-up da proposta enviada", daysFromNow: 2, priority: "medium" },
  },
  {
    id: "00000000-0000-4000-8000-000000000219",
    name: "Ricardo Nogueira",
    company: "Nogueira Auto Peças",
    jobTitle: "Proprietário",
    city: "Itapema",
    email: "ricardo.nogueira@nogueiraautopecas.demo",
    phone: "47999011019",
    stageKey: "proposta",
    ownerIndex: null,
    potentialValue: 9800,
    score: 70,
    tags: ["automotivo", "proposta enviada"],
    daysAgoCreated: 17,
    daysInStage: 4,
    lastInteractionDaysAgo: 3,
    utm: LINKEDIN_CAMPAIGN,
  },
  {
    id: "00000000-0000-4000-8000-000000000220",
    name: "Tatiane Correia",
    company: "Correia Studio de Pilates",
    jobTitle: "Fundadora",
    city: "Florianópolis",
    email: "tatiane.correia@correiapilates.demo",
    phone: "47999011020",
    stageKey: "proposta",
    ownerIndex: 2,
    potentialValue: 6700,
    score: 72,
    tags: ["fitness", "proposta enviada"],
    daysAgoCreated: 15,
    daysInStage: 3,
    lastInteractionDaysAgo: 1,
    utm: ORGANIC,
    nextTask: { title: "Follow-up da proposta enviada", daysFromNow: 0, priority: "medium" },
  },

  // ---- Fechado (won → become clients) ----
  {
    id: "00000000-0000-4000-8000-000000000221",
    name: "Alexandre Brito",
    company: "Brito Farmácias",
    jobTitle: "Diretor de Expansão",
    city: "Joinville",
    email: "alexandre.brito@britofarmacias.demo",
    phone: "47999011021",
    stageKey: "fechado",
    ownerIndex: 1,
    potentialValue: 42000,
    score: 92,
    tags: ["saúde", "cliente"],
    daysAgoCreated: 40,
    daysInStage: 6,
    lastInteractionDaysAgo: 1,
    utm: GOOGLE_CAMPAIGN,
    becameClient: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000222",
    name: "Priscila Fagundes",
    company: "Fagundes Salão & Spa",
    jobTitle: "Proprietária",
    city: "Brusque",
    email: "priscila.fagundes@fagundesspa.demo",
    phone: "47999011022",
    stageKey: "fechado",
    ownerIndex: 3,
    potentialValue: 8200,
    score: 88,
    tags: ["beleza", "cliente"],
    daysAgoCreated: 35,
    daysInStage: 8,
    lastInteractionDaysAgo: 2,
    utm: META_CAMPAIGN,
    becameClient: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000223",
    name: "Otávio Peixoto",
    company: "Peixoto Consultoria Empresarial",
    jobTitle: "Sócio-diretor",
    city: "Florianópolis",
    email: "otavio.peixoto@peixotoconsultoria.demo",
    phone: "47999011023",
    stageKey: "fechado",
    ownerIndex: null,
    potentialValue: 19500,
    score: 85,
    tags: ["consultoria", "cliente"],
    daysAgoCreated: 50,
    daysInStage: 10,
    lastInteractionDaysAgo: 3,
    utm: LINKEDIN_CAMPAIGN,
    becameClient: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000224",
    name: "Débora Anjos",
    company: "Anjos Móveis Planejados",
    jobTitle: "Diretora Comercial",
    city: "Itajaí",
    email: "debora.anjos@anjosmoveis.demo",
    phone: "47999011024",
    stageKey: "fechado",
    ownerIndex: 2,
    potentialValue: 27800,
    score: 90,
    tags: ["varejo", "cliente"],
    daysAgoCreated: 28,
    daysInStage: 4,
    lastInteractionDaysAgo: 1,
    utm: ORGANIC,
    becameClient: true,
  },

  // ---- Perdido (lost — orthogonal to stage, excluded from Pipeline) ----
  {
    id: "00000000-0000-4000-8000-000000000225",
    name: "Wagner Siqueira",
    company: "Siqueira Materiais Elétricos",
    jobTitle: "Proprietário",
    city: "Joinville",
    email: "wagner.siqueira@siqueiraeletrica.demo",
    phone: "47999011025",
    stageKey: "proposta",
    ownerIndex: 1,
    potentialValue: 9200,
    score: 40,
    tags: ["varejo"],
    daysAgoCreated: 30,
    daysInStage: 12,
    lastInteractionDaysAgo: 12,
    lost: { reason: "preco", daysAgo: 6 },
    utm: GOOGLE_CAMPAIGN,
  },
  {
    id: "00000000-0000-4000-8000-000000000226",
    name: "Carla Prado",
    company: "Prado Boutique Infantil",
    jobTitle: "Proprietária",
    city: "Balneário Camboriú",
    email: "carla.prado@pradoboutique.demo",
    phone: "47999011026",
    stageKey: "contato",
    ownerIndex: null,
    potentialValue: 4100,
    score: 22,
    tags: ["varejo"],
    daysAgoCreated: 22,
    daysInStage: 15,
    lastInteractionDaysAgo: 15,
    lost: { reason: "nao_respondeu", daysAgo: 4 },
    utm: TIKTOK_CAMPAIGN,
  },
  {
    id: "00000000-0000-4000-8000-000000000227",
    name: "Leonardo Vasconcelos",
    company: "Vasconcelos Corretora de Seguros",
    jobTitle: "Corretor Responsável",
    city: "Florianópolis",
    email: "leonardo.vasconcelos@vasconcelosseg.demo",
    phone: "47999011027",
    stageKey: "qualificado",
    ownerIndex: 3,
    potentialValue: 13500,
    score: 45,
    tags: ["seguros"],
    daysAgoCreated: 26,
    daysInStage: 10,
    lastInteractionDaysAgo: 9,
    lost: { reason: "concorrente", daysAgo: 3 },
    utm: LINKEDIN_CAMPAIGN,
  },
];

/** Clients not tied to a demo lead conversion — pre-existing accounts, to
 * make the Clientes screen look like an established base rather than one
 * that only ever grows from won leads. */
export const DEMO_STANDALONE_CLIENTS = [
  {
    id: "00000000-0000-4000-8000-000000000301",
    company: "Grupo Litoral Hotéis",
    name: "Vinícius Amaral",
    email: "vinicius.amaral@grupolitoral.demo",
    phone: "47999022001",
    ownerIndex: 0,
    status: "ativo" as const,
    daysAgoCreated: 210,
  },
  {
    id: "00000000-0000-4000-8000-000000000302",
    company: "Bella Vita Restaurantes",
    name: "Marina Souto",
    email: "marina.souto@bellavita.demo",
    phone: "47999022002",
    ownerIndex: 1,
    status: "ativo" as const,
    daysAgoCreated: 180,
  },
  {
    id: "00000000-0000-4000-8000-000000000303",
    company: "Construtora Horizonte",
    name: "Paulo Renato",
    email: "paulo.renato@horizonteconstrutora.demo",
    phone: "47999022003",
    ownerIndex: null,
    status: "em_risco" as const,
    daysAgoCreated: 260,
  },
  {
    id: "00000000-0000-4000-8000-000000000304",
    company: "Estúdio Criativo Nova Era",
    name: "Beatriz Lacerda",
    email: "beatriz.lacerda@novaeraestudio.demo",
    phone: "47999022004",
    ownerIndex: 2,
    status: "inativo" as const,
    daysAgoCreated: 320,
  },
];
